name: Deploy React App to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 📦 Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 🔨 Build React App
        working-directory: ./sinergify/frontend   # 👈 point to frontend
        run: |
          npm install
          npm run build

      - name: 🔑 Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: 🚀 Deploy to VPS
        run: |
          rsync -avz --delete \
            sinergify/frontend/build/ \   # 👈 point to the correct build folder
            agmqykay2a98@118.139.176.89:/home/agmqykay2a98/public_html/
